config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users

  # home page route
  root "listings#index"
  

  
  # nested resources as listings belong to coach 
  resources :coaches do 
    resources :listings
  end

  # manual route for listing creation as answer to nested resource issues
  post '/coaches/:coach_id/listings', to: 'listings#create', as: 'create_listing'

  # profile page route
  get '/users/profile', to: 'users#show', as: "profile"

  
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.coach?
        can :manage, Listing, user_id: user.id    
      else
        can :read, Listing, :manage, User, user_id: user.id
      end
  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
  has_many :listings
  belongs_to :user

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :coach
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :picture
  has_one :coach, dependent: :destroy
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # attempts at authorisation global helper
  def authorize
    if current_user.nil?
      flash[:alert] = "You are not authorised to perform that action!"
      redirect_to root_path
    end
  end

  def authorise_coach
    return if @coach.can_edit?(current_user)
    
    flash[:alert] = "You are not authorised to perform that action!"
    redirect_to root_path
  end
  
  protected
  # allow picture through params pass devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:picture)
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  # set @coach as current coach as received by params in the following methods
  before_action :find_coach, only: [:show, :edit, :update, :delete]

  def index
  end

  
  def show
  end

  def new
    @coach = Coach.new
  end

  def create
    # Create new coach with strong params private methods
    @coach = Coach.new(strongparams)
    # set user id foreign of new coach to current user
    @coach.user_id = current_user
    @coach.save
    
    redirect_to coach_path(@coach)
  end
  

  def edit
  end

  def update
  
  end

  def delete

  end

  private 
  def find_coach
    @coach = Coach.find(params[:id])
  end

  def strongparams
    params.require(:coach).permit(:business_name, :children_check, :business_mobile, :bio)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # set @coach as current coach as received by params in the following methods
  before_action :set_listing, only: [:show]
  # Prevents site visitors from access to the following methods
  before_action :authenticate_user!, only: [:edit, :update, :delete]

  def index
    @listings = Listing.all

  end

  

  def show
  
  end
  
  def new
    @listing = Listing.new
    params
    @coach = Coach.find(params[:coach_id])
    
    
  end

  def create
    # set @coach to id of current logged in coach 
    @coach = Coach.find(params[:coach_id])
    # create new listing with strong params private methods
    @listing = Listing.new(strongparams)
    # make coach foreign key in new listing as current logged in coach 
    @listing.coach_id = @coach.id
    # flash and alerts for creation success or failure
    if @listing.save! 
      flash[:notice] = "Listing created successfully"
      redirect_to coach_listing_path(@coach, @listing)
    else 
      flash.now[:alert] = "Listing was not created"
      render "new"
    end 

    
  end
  

  def edit
  end

  def update
  
  end

  def delete
    @listing.destroy
    # text on screen for deletion confirmation
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'The listing has been deleted.' }
      format.json { head :no_content }
    end

  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end


  def strongparams
    params.require(:listing).permit(:title, :description, :price, :term, :location, :picture, :coach_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    
  end

  def edit 
    
  end
    
  def update

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coaches/_form.html.erb
<%= form_with(model: coach, local: true) do |form| %>

    <div class="field">
        <%= form.label :business_name %>
        <%= form.text_field :business_name %>
    </div>

    <div class="field">
        <%= form.label :business_mobile %>
        <%= form.telephone_field :business_mobile %>
    </div>    

    <div class="field">
        <%= form.label :bio %>
        <%= form.text_area :bio %>
    </div>
    
    <div class="field">
        <%= form.label :children_check %>
        <%= form.check_box :children_check %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form', coach: @coach%>

<%# Delete coach link with confirmation%>
<%= link_to "Delete coach profile", coach_path, method: "delete", data: {confirm: "Are you sure?"}%>


<section >
<%= link_to 'Home', root_path %>
<p> | </p>
<%= link_to 'Cancel Edit', @coach %>
</section>

app/views/coaches/index.html.erb
<h1>All coaches</h1>

app/views/coaches/new.html.erb
<%= render 'form', coach: @coach%>

app/views/coaches/show.html.erb
<h1>Your Coach</h1>

<%= @coach.business_name%>
<%= @coach.bio%>

<%# only the coach displayed is allowed to edit this page%>
<% if :authorize_coach %>
  <%= link_to "Edit your coach ", edit_coach_path(@coach)%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchmaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <% if user_signed_in? %>
      <%= link_to "logout", destroy_user_session_path, method:"delete" %>
      <%= link_to "profile", profile_path %>
    <% else %>
      <%= link_to "login", new_user_session_path %>
    <% end %>
      <%= link_to "All listings", root_path %>
    <% flash.each do |key, message| %>
      <div><%= message %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: @listing, url: create_listing_path(@coach)) do |form| %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div class="field">
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>

    <div class="field">
        <%= form.label :term_weeks %>
        <%= form.number_field :term %>
    </div>

    <div class="field">
        <%= form.label :location %>
        <%= form.text_area :location %>
    </div>

    <div>
    <%= form.label :picture %> <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg'%>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/edit.html.erb
<%= render 'form', listing: @listing%>

<%# Delete listing link with confirmation%>
<%= link_to "Delete Listing", coach_listing_path, method: "delete", data: {confirm: "Are you sure?"}%>


<section >
<%= link_to 'Home', root_path %>
<p> | </p>
<%= link_to 'Cancel Edit', @listing %>
</section>

app/views/listings/index.html.erb
<h1>All listings</h1>

<%# show all listings individually and add view link%>
<% @listings.each do |listing| %>
  <%=listing.title%>
  <%=listing.description%>
    <% if listing.picture.attached?%>
    <%= image_tag listing.picture, width: 250, class: "img_btn"%>
  <% end %>

    <%= link_to 'View', coach_listing_path(listing.coach_id, listing) %>
  <br><br>

<% end %>

app/views/listings/new.html.erb
<%= render 'form', listing: @listing%>

app/views/listings/show.html.erb
<%# Display data about the single listing%>

<%= @listing.title %>
<%= @listing.description%>

<p><%= image_tag(@listing.picture, width: 250) if @listing.picture.attached? %></p>
<%#  if current_user.coach_id == @listing.coach.user_id%>
<%# <%= link_to "edit", edit_coach_listing_path(@listing.id)  %>
<%# <% end %> 

app/views/users/profile.html.erb
<h1> Welcome back</h1>

<%= current_user.email %>

app/views/users/show.html.erb
<h1> Welcome back</h1>

<%= current_user.email %>

<%= link_to "Edit profile details", edit_user_registration_path(current_user) %>

<%= image_tag current_user.picture if current_user.picture.attached? %>

<%= link_to "Apply as a coach", new_coach_path%>

<%= link_to "Coach profile", coach_path(current_user)%>